EXTRA_COMPONENT_DIRS += $(SOLUTION_PATH)/components
EXTRA_COMPONENT_DIRS += $(SOLUTION_PATH)/components/gpio_fast
EXTRA_COMPONENT_DIRS += $(SOLUTION_PATH)/components/LED
EXTRA_COMPONENT_DIRS += $(SOLUTION_PATH)/components/LCD
EXTRA_COMPONENT_DIRS += $(SOLUTION_PATH)/components/CONFIG
EXTRA_COMPONENT_DIRS += $(SOLUTION_PATH)/components/YMCV
